import Footer from '@/components/shared/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/shared/Navbar'
import AuthProvider from '@/components/AuthProvider/AuthProvider'
import Providers from '@/lib/ThemeProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kodejob',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='dark:bg-slate-900'>
        <AuthProvider>
        <Providers>
        <Navbar/>
        {children}
        <Footer/>
        </Providers>
        </AuthProvider>
        </body>
    </html>
  )
}
