import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import LoginComp from "@/components/login_comp/LoginComp"
import { getServerSession } from "next-auth"
import { redirect } from "next/navigation"


export const metadata = {
  title: 'login',
  description: 'Generated by create next app',
}


const page = async () => {
  const session = await getServerSession(authOptions);
  if(session){
    redirect('/')
  }
  return (
    <LoginComp/>
    )
}

export default page