

// import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import Postjob_Comp from "@/components/post_comp/Postjob_Comp";
// import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Job Post",
  description: "Generated by create next app",
};

const Post_Job = async () => {
  // const [image, setImage] = useState([]);
// 
  // const session = await getServerSession(authOptions);
  // console.log(session);
  // if (!session) {
  //   redirect("/login");
  // }


  return <Postjob_Comp sessionData={'6505c0a7dd2616289b57e7d2'} />;
};

export default Post_Job;
